# The Iris Dataset
The data set consists of 50 samples from each of three species of Iris (Iris setosa, Iris virginica and Iris versicolor). Four features were measured from each sample: the length and the width of the sepals and petals, in centimeters.

The dataset contains a set of 150 records under five attributes - petal length, petal width, sepal length, sepal width and species.

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [206]:
%tensorflow_version 2.x

UsageError: Line magic function `%tensorflow_version` not found.


### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [207]:
import tensorflow as tf
print(tf.__version__)

2.1.0


### Set random seed

In [208]:
tf.random.set_seed(42)

## Question 1

### Import dataset
- Import iris dataset
- Import the dataset using sklearn library

In [209]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
data = load_iris()

## Question 2

### Get features and label from the dataset in separate variable
- you can get the features using .data method
- you can get the features using .target method

In [210]:
X=data.data
y=data.target

## Question 3

### Create train and test data
- use train_test_split to get train and test set
- set a random_state
- test_size: 0.25

In [55]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=1)

## Question 4

### One-hot encode the labels
- convert class vectors (integers) to binary class matrix
- convert labels
- number of classes: 3
- we are doing this to use categorical_crossentropy as loss

In [56]:
from tensorflow.keras.utils import to_categorical

y_train=to_categorical(y_train,num_classes=3)
y_test=to_categorical(y_test,num_classes=3)

y_train

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1

## Question 5

### Initialize a sequential model
- Define a sequential model

In [57]:
from tensorflow.keras import layers
model=tf.keras.Sequential()

## Question 6

### Add a layer
- Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3
- Apply Softmax on Dense Layer outputs

In [58]:
from tensorflow.keras.layers import Dense

model.add(Dense(4,activation='sigmoid',input_shape=(4,)))

model.add(Dense(3,activation='softmax'))

In [59]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 4)                 20        
_________________________________________________________________
dense_1 (Dense)              (None, 3)                 15        
Total params: 35
Trainable params: 35
Non-trainable params: 0
_________________________________________________________________


## Question 7

### Compile the model
- Use SGD as Optimizer
- Use categorical_crossentropy as loss function
- Use accuracy as metrics

In [60]:
sgd=tf.keras.optimizers.SGD(lr=0.1,decay=0.000225,momentum=0.5)
model.compile(optimizer=sgd,
             loss='categorical_crossentropy',
             metrics=['accuracy'])

## Question 8

### Summarize the model
- Check model layers
- Understand number of trainable parameters

In [61]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 4)                 20        
_________________________________________________________________
dense_1 (Dense)              (None, 3)                 15        
Total params: 35
Trainable params: 35
Non-trainable params: 0
_________________________________________________________________


## Question 9

### Fit the model
- Give train data as training features and labels
- Epochs: 100
- Give validation data as testing features and labels

In [62]:
model.fit(X_train,y_train,batch_size=200,epochs=100,verbose=1,validation_data=(X_test,y_test))

Train on 112 samples, validate on 38 samples
Epoch 1/100
112/112 [==============================] - 1s 6ms/sample - loss: 1.1527 - accuracy: 0.3661 - val_loss: 1.2218 - val_accuracy: 0.2368
Epoch 2/100
112/112 [==============================] - 0s 100us/sample - loss: 1.1392 - accuracy: 0.3661 - val_loss: 1.1939 - val_accuracy: 0.2368
Epoch 3/100
112/112 [==============================] - 0s 100us/sample - loss: 1.1218 - accuracy: 0.3661 - val_loss: 1.1670 - val_accuracy: 0.3684
Epoch 4/100
112/112 [==============================] - 0s 122us/sample - loss: 1.1053 - accuracy: 0.3929 - val_loss: 1.1438 - val_accuracy: 0.5789
Epoch 5/100
112/112 [==============================] - 0s 119us/sample - loss: 1.0906 - accuracy: 0.6875 - val_loss: 1.1246 - val_accuracy: 0.5789
Epoch 6/100
112/112 [==============================] - 0s 105us/sample - loss: 1.0775 - accuracy: 0.6786 - val_loss: 1.1084 - val_accuracy: 0.5789
Epoch 7/100
112/112 [==============================] - 0s 122us/sample - lo

## Question 10

### Make predictions
- Predict labels on one row

In [72]:
y_predict = model.predict(X_test)
y_predict[0:1]

array([[0.8162594 , 0.13864358, 0.04509699]], dtype=float32)

### Compare the prediction with actual label
- Print the same row as done in the previous step but of actual labels

In [73]:
y_test[0:1]

array([[1., 0., 0.]], dtype=float32)



---



# Stock prices dataset
The data is of tock exchange's stock listings for each trading day of 2010 to 2016.

## Description
A brief description of columns.
- open: The opening market price of the equity symbol on the date
- high: The highest market price of the equity symbol on the date
- low: The lowest recorded market price of the equity symbol on the date
- close: The closing recorded price of the equity symbol on the date
- symbol: Symbol of the listed company
- volume: Total traded volume of the equity symbol on the date
- date: Date of record

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [142]:
%tensorflow_version 2.x

UsageError: Line magic function `%tensorflow_version` not found.


### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [247]:
import tensorflow as tf
print(tf.__version__)

2.1.0


### Set random seed

In [248]:
tf.random.set_seed(42)

## Question 1

### Load the data
- load the csv file and read it using pandas
- file name is prices.csv

In [270]:
prices_df=pd.read_csv("prices.csv")
prices_df

date symbol        open       close         low  \
0       2016-01-05 00:00:00   WLTW  123.430000  125.839996  122.309998   
1       2016-01-06 00:00:00   WLTW  125.239998  119.980003  119.940002   
2       2016-01-07 00:00:00   WLTW  116.379997  114.949997  114.930000   
3       2016-01-08 00:00:00   WLTW  115.480003  116.620003  113.500000   
4       2016-01-11 00:00:00   WLTW  117.010002  114.970001  114.089996   
...                     ...    ...         ...         ...         ...   
851259           2016-12-30    ZBH  103.309998  103.199997  102.849998   
851260           2016-12-30   ZION   43.070000   43.040001   42.689999   
851261           2016-12-30    ZTS   53.639999   53.529999   53.270000   
851262  2016-12-30 00:00:00    AIV   44.730000   45.450001   44.410000   
851263  2016-12-30 00:00:00    FTV   54.200001   53.630001   53.389999   

              high     volume  
0       126.250000  2163600.0  
1       125.540001  2386400.0  
2       119.739998  2489500.0  
3       117.440002  2006300.0  
4       117.330002  1408600.0  
...            ...        ...  
851259  103.930000   973800.0  
851260   43.310001  1938100.0  
851261   53.740002  1701200.0  
851262   45.590000  1380900.0  
851263   54.480000   705100.0  

[851264 rows x 7 columns]

## Question 2

### Drop columnns
- drop "date" and "symbol" column from the data

In [271]:
prices_df=prices_df.drop(['date','symbol'], axis = 1)


## Question 3

### Take initial rows
- Take first 1000 rows from the data
- This step is done to make the execution faster

In [272]:
prices_df=prices_df.iloc[0:1000,:]
prices_df.shape

(1000, 5)

In [252]:
prices_df.head()

open       close         low        high     volume
0  123.430000  125.839996  122.309998  126.250000  2163600.0
1  125.239998  119.980003  119.940002  125.540001  2386400.0
2  116.379997  114.949997  114.930000  119.739998  2489500.0
3  115.480003  116.620003  113.500000  117.440002  2006300.0
4  117.010002  114.970001  114.089996  117.330002  1408600.0

## Question 4

### Get features and label from the dataset in separate variable
- Take "open", "close", "low", "high" columns as features
- Take "volume" column as label
- Normalize label column by dividing it with 1000000

In [273]:
features=prices_df.iloc[:,0:4]
label=prices_df.loc[:,'volume']

In [274]:
label=label/1000000
label

0       2.1636
1       2.3864
2       2.4895
3       2.0063
4       1.4086
        ...   
995     2.1332
996     1.9824
997    37.1528
998     6.5686
999     5.6043
Name: volume, Length: 1000, dtype: float64

## Question 5

### Convert data
- Convert features and labels to numpy array
- Convert their data type to "float32"

In [275]:
features=np.asarray(features)

In [276]:
label=np.asarray(label)

In [285]:
features=features.astype('float32')
features.dtype

dtype('float32')

In [286]:
label=label.astype('float32')
label.dtype

dtype('float32')

## Question 6

### Normalize data
- Normalize features
- Use tf.math.l2_normalize to normalize features
- You can read more about it here https://www.tensorflow.org/api_docs/python/tf/math/l2_normalize

In [288]:
tf.math.l2_normalize(
    features,
    axis=None,
    epsilon=1e-12,
    name=None
)

<tf.Tensor: shape=(1000, 4), dtype=float32, numpy=
array([[0.02202894, 0.02245906, 0.02182905, 0.02253223],
       [0.02235197, 0.02141321, 0.02140607, 0.02240551],
       [0.0207707 , 0.02051548, 0.02051192, 0.02137037],
       ...,
       [0.00505436, 0.00513467, 0.00499903, 0.00514181],
       [0.00785282, 0.0079956 , 0.0078082 , 0.00799738],
       [0.00643931, 0.00662849, 0.00642682, 0.00664455]], dtype=float32)>

## Question 7

### Define weight and bias
- Initialize weight and bias with tf.zeros
- tf.zeros is an initializer that generates tensors initialized to 0
- Specify the value for shape

In [289]:
W=tf.zeros(shape=(4,1))
b=tf.zeros(shape=(1))

## Question 8

### Get prediction
- Define a function to get prediction
- Approach: prediction = (X * W) + b; here is X is features

In [290]:
@tf.function
def prediction(features,W,b):
    y_pred=tf.add(tf.matmul(features,W),b)
    return y_pred

### Calculate loss
- Calculate loss using predictions
- Define a function to calculate loss
- We are calculating mean squared error

In [291]:
@tf.function
def loss(y_actual,y_predicted):
    diff=y_actual-y_predicted
    sqr=tf.square(diff)
    avg=tf.reduce_mean(sqr)
    return avg

## Question 9

### Define a function to train the model
1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

In [301]:
def train(x,y_actual,w,b,learning_rate=0.01):
    
    with tf.GradientTape() as t:
        t.watch([w,b])
        current_prediction=prediction(x,w,b)
        current_loss=loss(y_actual,current_prediction)
        
    dw,db=t.gradient(current_loss,[w,b])
    
    w=w-learning_rate * dw
    b=b-learning_rate * db
    
    return w,b

## Question 10

### Train the model for 100 epochs 
- Observe the training loss at every iteration

In [302]:
for i in range(100):
    W,b=train(X,y,W,b)
    print('Current Training Loss on iteration',i,loss(y,prediction(X,W,b).numpy()))

TypeError: in converted code:

    <ipython-input-290-3baa115922f6>:3 prediction  *
        y_pred=tf.add(tf.matmul(features,W),b)
    /Users/nikhilkanojia/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/util/dispatch.py:180 wrapper
        return target(*args, **kwargs)
    /Users/nikhilkanojia/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/math_ops.py:2798 matmul
        a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
    /Users/nikhilkanojia/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_math_ops.py:5626 mat_mul
        name=name)
    /Users/nikhilkanojia/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/framework/op_def_library.py:504 _apply_op_helper
        inferred_from[input_arg.type_attr]))

    TypeError: Input 'b' of 'MatMul' Op has type float32 that does not match type float64 of argument 'a'.


### Observe values of Weight
- Print the updated values

In [298]:
print(W)

tf.Tensor(
[[0.]
 [0.]
 [0.]
 [0.]], shape=(4, 1), dtype=float32)


### Observe values of Bias
- Print the updated values

In [299]:
print(b)

tf.Tensor([0.], shape=(1,), dtype=float32)
